/**
 * Jobs Express
 * This is a sample Express Jobs server. You can find out more about Express Jobs at [https://drive.google.com/drive/folders/1VyQ8tqiA7Q2J0zhWDIwg581wJdBFusmK?usp=sharing)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@ExpressJobs.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.trabajosexpres.Model

/**
 *
 * @param accountStatus status of account
 * @param accountType type of account
 */
data class AccountType (
        /* ID of AccountType */
        val idAccountType: kotlin.Int,
        /* status of account */
        val accountStatus: AccountStatus,
        /* type of account */
        val accountType: AccountType
) {
    /**
     * status of account
     * Values: ACTIVE,INACTIVE,BLOCKEDUP
     */
    enum class AccountStatus(val value: kotlin.String){
        ACTIVE("Active"),
        INACTIVE("Inactive"),
        BLOCKEDUP("BlockedUp");
    }
    /**
     * type of account
     * Values: CLIENT,EMPLOYEE,MANAGER
     */
    enum class AccountType(val value: kotlin.String){
        CLIENT("Client"),
        EMPLOYEE("Employee"),
        MANAGER("Manager");
    }
}