/**
 * Jobs Express
 * This is a sample Express Jobs server. You can find out more about Express Jobs at [https://drive.google.com/drive/folders/1VyQ8tqiA7Q2J0zhWDIwg581wJdBFusmK?usp=sharing)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@ExpressJobs.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.trabajosexpres.Model


/**
 *
 * @param id Id of Cost
 * @param cost cost
 * @param currency currency of cost
 */
data class Cost (

        /* Id of Cost */
        val id: kotlin.Long? = null,
        /* cost */
        val cost: java.math.BigDecimal,
        /* currency of cost */
        val currency: Cost.Currency
) {
    /**
     * currency of cost
     * Values: MXN
     */
    enum class Currency(val value: kotlin.String){
        MXN("MXN");
    }
}