/**
 * Jobs Express
 * This is a sample Express Jobs server. You can find out more about Express Jobs at [https://drive.google.com/drive/folders/1VyQ8tqiA7Q2J0zhWDIwg581wJdBFusmK?usp=sharing)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@ExpressJobs.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.trabajosexpres.Model

/**
 *
 * @param id ID of MemberATE
 * @param email Email of MemberATE
 * @param dateBirth Date birth of MemberATE
 * @param lastName lastName of MemberATE
 * @param name name of MemberATE
 * @param resource
 */
data class MemberATE (

        /* ID of MemberATE */
        val id: Int = 0,
        /* Email of MemberATE */
        val email: kotlin.String,
        /* Date birth of MemberATE */
        val dateBirth: String,
        /* lastName of MemberATE */
        val lastName: kotlin.String,
        /* name of MemberATE */
        val name: kotlin.String,
        val username: String,
        /* encrypted password */
        val password: String,
        /*Type of Account*/
        val accountType: Int,
        val idCity: Int,
        val memberATEStatus:Int
) {
}