/**
 * Jobs Express
 * This is a sample Express Jobs server. You can find out more about Express Jobs at [https://drive.google.com/drive/folders/1VyQ8tqiA7Q2J0zhWDIwg581wJdBFusmK?usp=sharing)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@ExpressJobs.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.trabajosexpres.Model

/**
 *
 * @param id ID of rating
 * @param comment comment of ranting
 * @param rating rating
 * @param request
 */
data class Rating (

        /* ID of rating */
        val id: kotlin.Long? = null,
        /* comment of ranting */
        val comment: kotlin.String,
        /* rating */
        val rating: kotlin.Long,
        val request: Request? = null
) {
}