/**
 * Jobs Express
 * This is a sample Express Jobs server. You can find out more about Express Jobs at [https://drive.google.com/drive/folders/1VyQ8tqiA7Q2J0zhWDIwg581wJdBFusmK?usp=sharing)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@ExpressJobs.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.trabajosexpres.Model

/**
 *
 * @param isMainResource It is the main resource
 * @param routeSave path where the resource was saved
 * @param name name of resource
 * @param service
 */
data class Resource (

        /* It is the main resource */
        val isMainResource: kotlin.Boolean? = null,
        /* path where the resource was saved */
        val routeSave: kotlin.String? = null,
        /* name of resource */
        val name: kotlin.String,
        val service: Service
) {
}