/**
 * Jobs Express
 * This is a sample Express Jobs server. You can find out more about Express Jobs at [https://drive.google.com/drive/folders/1VyQ8tqiA7Q2J0zhWDIwg581wJdBFusmK?usp=sharing)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@ExpressJobs.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.trabajosexpres.Model

/**
 *
 * @param id ID of service
 * @param city
 * @param country
 * @param state
 * @param memberATE
 * @param name name of sevice
 * @param minimalCost
 * @param maximumCost
 * @param descriptionService description of sevice
 * @param slogan slogan of sevice
 * @param typeService type of sevice
 * @param workingHours Service hours
 * @param serviceStatus service status
 */
data class Service (

        /* ID of service */
        val idService: Int = 0,
        val idCity: Int,
        val idMemberATE: Int,
        /* name of sevice */
        val name: kotlin.String,
        val minimalCost: Double,
        val maximumCost: Double,
        /* description of sevice */
        val descriptionService: kotlin.String,
        /* slogan of sevice */
        val slogan: kotlin.String,
        /* type of sevice */
        val typeService: kotlin.String,
        /* Service hours */
        val workingHours: kotlin.String,
        /* service status */
        val serviceStatus: Int
)